# Generated by Django 2.2.3 on 2019-07-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emp',
            table='student',
        ),
    ]
