# Generated by Django 2.2.3 on 2019-07-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190703_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
