# Generated by Django 2.2.3 on 2019-07-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_emp_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='image',
        ),
    ]
